data_dir: ./data
seed: 100
image_size: 12
batch_size: 20
epochs: 100
n_figures: 10
n_samples: 400
n_qubits: 8
n_layers: 22
latent_size: 100
disc_lr: 0.0002
gen_lr: 0.0002
generator_update_step: 3
noise_gain: 0.5
noise_offset: 0.0
selected_label: 0
tracking_uri: http://127.0.0.1:5000
log_level: INFO